### ISSUE TITLE
Watch for WM_PAINT instead of updating every 10ms

### ISSUE THREAD

**Issue by ethanhs** [ethanhs/TranslucentTB#5]
Its rather inefficient to update every 10ms. @charlesmilette, you had mentioned you had looked at this. Did you attempt this? I think I am going to subclass the taskbar if I can.

**Comment by charlesmilette** [comment]
I attempted a hook with `SetWindowsHookEx`, but with lack of C++ experience, it got wrong.

Instead, I made a quite interesting find. If you create a window with the same size and position than the taskbar, and set it as parent of the taskbar, the taskbar will use this as background instead of the default transparent dark. There's a lot of bugs with this tho:

- The taskbar disappears when using Aero Peek
- The taskbar disappears when using Win+Tab
- Some programs basing their activity on the taskbar will crash
- If you try to resize or move the taskbar, it really messes up

**Comment by ethanhs** [comment]
@charlesmilette Hm, that is an issue. What if it is not a regular Window?I believe if you set the `WS_EX_TOOLWINDOW` it won't show up in AeroPeek/WinTab.

**Comment by charlesmilette** [comment]
I mean is that you just can't see it at all when using the feature, while normally it would appear. For example, you can still see the taskbar over the desktop while using Aero Peek. In my case, you couldn't see it.

I tried changing it so that it still shows when using those features, but for a random reason it still disappeared.

Another issue: if you closed the program managing the parent window of the taskbar, the taskbar would also get destroyed.

**Comment by ethanhs** [comment]
Hm, okay that isn't acceptable. I think I'll try to use SetWindowHookEx myself and see where I get.

**Comment by ethanhs** [comment]
I ran a battery test and did not find any significant difference in usage. If someone has a reason and a more scientific test of battery life, please comment and I will re-open this, otherwise I think I'll wontfix this for now.
